### ISSUE TITLE
Implement asset location tracking

### ISSUE THREAD

**Issue by richturner** [openremote/openremote#63]
First see:

[Architecture:-Asset-location-tracking](https://github.com/openremote/openremote/wiki/Architecture:-Asset-location-tracking), this issue is here to capture implementation steps:

## Rules infrastructure
- [x] Ability to identify rules which have location predicates in them and to be able to interrogate the assets that these rules apply to - 24hrs
- [x] Asset persistence monitoring of assets in scope of location predicate rules and subscription mechanism for asset refresh - 8hrs
- [x] Monitoring of location predicate rules and subscription mechanism for asset refresh - 8hrs

## Geofence infrastructure
- [x] Define geofence model (backend) - 16hrs
- [x] Define attribute(s) and attribute value(s) to be used by assets that support geofencing APIs (backend) - 8hrs
- [x] Define interface for geofence adapters (backend) - 8hrs
- [x] Implement OpenRemote console geofence adapter (backend) - 20hrs
- [x] Implement geofence console code (Android; depends on #76) - 24hrs
- [x] Implement geofence console code (iOS; depends on #76) - 24hrs
- [x] Implement RulesResource `geofence` JAX-RS endpoint (backend) - 16hrs
- [x] Mechanism for pushing geofence refreshes to Android and iOS using push notification topic(s) (backend; depends on #52) - 16hrs

**Comment by richturner** [comment]
This is currently implemented in Beatrixkanaal console app where the backend uses topic push notification through GCM to tell the mobile devices to re-fetch and update their geofence definitions; the definition also contains the action to perform when a geofence triggers; it does not combine geofence trigger with other triggers. See below for geofence rule definition JSON:

```json
[
    {
        "id": 36,
        "markerId": 869,
        "uuid": "a0d63148bf0486af095423aeb1cd922490ad9bf4",
        "active": true,
        "trigger": null,
        "target": null,
        "contact": null,
        "action": "NOTIFICATION",
        "actionData": {
            "title": "Registreren Kano vereniging",
            "text": "Vergeet je niet te registreren als je het water opgaat. Voor je eigen veiligheid en die van anderen.",
            "openAppOnClick": true,
            "openData": "register"
        },
        "primaryTrigger": {
            "type": "SPATIAL",
            "parameters": {
                "latitude": 51.436728062471076,
                "longitude": 5.4329752922058105,
                "radius": 50,
                "transition": "ENTER"
            }
        },
        "conditions": [
        ]
    },
    {
        "id": 37,
        "markerId": 870,
        "uuid": "0bb399cf2daa587ef410f0377c7817a285b6c361",
        "active": true,
        "trigger": null,
        "target": null,
        "contact": null,
        "action": "NOTIFICATION",
        "actionData": {
            "title": "Registreren op het Beatrix kanaal",
            "text": "Vergeet je niet te registreren bij gebruik van het Beatrix kanaal. Voor je eigen veiligheid en die van anderen.",
            "openAppOnClick": true,
            "openData": "register"
        },
        "primaryTrigger": {
            "type": "SPATIAL",
            "parameters": {
                "latitude": 51.49184505854546,
                "longitude": 5.390998721122742,
                "radius": 50,
                "transition": "ENTER"
            }
        },
        "conditions": [
        ]
    },
    {
        "id": 38,
        "markerId": 871,
        "uuid": "b5a966a579b064f60b544b88f529bac7401fe80a",
        "active": true,
        "trigger": null,
        "target": null,
        "contact": null,
        "action": "NOTIFICATION",
        "actionData": {
            "title": "Herinnering Registreren Haven",
            "text": "Vergeet je niet te registreren bij gebruik van de haven. Er is een verplichting tot betalen van havengeld.",
            "openAppOnClick": true,
            "openData": "register"
        },
        "primaryTrigger": {
            "type": "SPATIAL",
            "parameters": {
                "latitude": 51.435015870212546,
                "longitude": 5.4376208782196045,
                "radius": 50,
                "transition": "ENTER"
            }
        },
        "conditions": [
        ]
    },
    {
        "id": 174,
        "markerId": 1007,
        "uuid": "2167e17619ae25ad4c07df58efb670dbe742aa05",
        "active": true,
        "trigger": null,
        "target": null,
        "contact": null,
        "action": "NOTIFICATION",
        "actionData": {
            "title": "Welkom op de Nachtegaallaan..",
            "text": "Je bent op het kantoor van de gemeente Eindhoven.",
            "openAppOnClick": true,
            "openData": "video"
        },
        "primaryTrigger": {
            "type": "SPATIAL",
            "parameters": {
                "latitude": 51.437798150042894,
                "longitude": 5.487528741359711,
                "radius": 50,
                "transition": "ENTER"
            }
        },
        "conditions": [
        ]
    },
    {
        "id": 212,
        "markerId": 1046,
        "uuid": "7f24972bde4a3c33374c10621789c526dd1f7e62",
        "active": true,
        "trigger": null,
        "target": null,
        "contact": null,
        "action": "NOTIFICATION",
        "actionData": {
            "title": "Genneperparken..",
            "text": "Welkom in Genneperparken",
            "openAppOnClick": true,
            "openData": "complaints"
        },
        "primaryTrigger": {
            "type": "SPATIAL",
            "parameters": {
                "latitude": 51.41655222144082,
                "longitude": 5.483529567718506,
                "radius": 100,
                "transition": "ENTER"
            }
        },
        "conditions": [
        ]
    }
]
```

**Comment by richturner** [comment]
Some more thoughts: 

- Have geofence as an asset type with attributes for fence type and size
- When an asset, console and/or any other definable 'thing' enters/exits/dwells within a geofence then generate a geofence trigger event

Can this be more coupled with rules?
For mobiles would need geofences to trigger on the device itself and notify the backend but this implementation detail should be abstracted away.
